package com.tripplanner.android.core.holidays

/** Indonesia public holidays (incl. cuti bersama). Ported from `data/holidays/id.ts`. */
internal val ID_HOLIDAYS: List<YearHolidays> = listOf(
    YearHolidays(
        year = 2025,
        country = CountryCode.ID,
        holidays = listOf(
            HolidayEntry(1, 1, "Tahun Baru Masehi"),
            HolidayEntry(1, 27, "Isra Mi'raj Nabi Muhammad"),
            HolidayEntry(1, 29, "Tahun Baru Imlek", listOf(CutiBersamaDay(1, 28))),
            HolidayEntry(3, 29, "Hari Suci Nyepi"),
            HolidayEntry(
                3, 31, "Idul Fitri",
                listOf(CutiBersamaDay(4, 1), CutiBersamaDay(4, 2), CutiBersamaDay(4, 3), CutiBersamaDay(4, 4)),
            ),
            HolidayEntry(4, 1, "Idul Fitri"),
            HolidayEntry(4, 18, "Wafat Isa Al Masih"),
            HolidayEntry(5, 1, "Hari Buruh"),
            HolidayEntry(5, 12, "Hari Raya Waisak"),
            HolidayEntry(5, 29, "Kenaikan Isa Al Masih"),
            HolidayEntry(6, 1, "Hari Lahir Pancasila"),
            HolidayEntry(6, 7, "Idul Adha", listOf(CutiBersamaDay(6, 9))),
            HolidayEntry(6, 27, "Tahun Baru Islam"),
            HolidayEntry(8, 17, "Hari Kemerdekaan"),
            HolidayEntry(9, 5, "Maulid Nabi Muhammad"),
            HolidayEntry(12, 25, "Hari Natal", listOf(CutiBersamaDay(12, 26))),
        ),
    ),
    YearHolidays(
        year = 2026,
        country = CountryCode.ID,
        holidays = listOf(
            HolidayEntry(1, 1, "Tahun Baru Masehi"),
            HolidayEntry(1, 16, "Isra Mi'raj Nabi Muhammad"),
            HolidayEntry(2, 17, "Tahun Baru Imlek"),
            HolidayEntry(3, 19, "Hari Suci Nyepi"),
            HolidayEntry(3, 20, "Idul Fitri", listOf(CutiBersamaDay(3, 23), CutiBersamaDay(3, 24))),
            HolidayEntry(3, 21, "Idul Fitri"),
            HolidayEntry(4, 3, "Wafat Isa Al Masih"),
            HolidayEntry(5, 1, "Hari Buruh"),
            HolidayEntry(5, 14, "Kenaikan Isa Al Masih"),
            HolidayEntry(5, 27, "Idul Adha"),
            HolidayEntry(5, 31, "Hari Raya Waisak"),
            HolidayEntry(6, 1, "Hari Lahir Pancasila"),
            HolidayEntry(6, 17, "Tahun Baru Islam"),
            HolidayEntry(8, 17, "Hari Kemerdekaan"),
            HolidayEntry(8, 26, "Maulid Nabi Muhammad"),
            HolidayEntry(12, 25, "Hari Natal", listOf(CutiBersamaDay(12, 24))),
        ),
    ),
    YearHolidays(
        year = 2027,
        country = CountryCode.ID,
        holidays = listOf(
            HolidayEntry(1, 1, "Tahun Baru Masehi"),
            HolidayEntry(1, 5, "Isra Mi'raj Nabi Muhammad"),
            HolidayEntry(2, 6, "Tahun Baru Imlek"),
            HolidayEntry(
                3, 9, "Idul Fitri",
                listOf(CutiBersamaDay(3, 10), CutiBersamaDay(3, 11), CutiBersamaDay(3, 12)),
            ),
            HolidayEntry(3, 10, "Idul Fitri"),
            HolidayEntry(3, 26, "Wafat Isa Al Masih"),
            HolidayEntry(3, 28, "Hari Suci Nyepi"),
            HolidayEntry(5, 1, "Hari Buruh"),
            HolidayEntry(5, 6, "Kenaikan Isa Al Masih"),
            HolidayEntry(5, 16, "Idul Adha"),
            HolidayEntry(5, 20, "Hari Raya Waisak"),
            HolidayEntry(6, 1, "Hari Lahir Pancasila"),
            HolidayEntry(6, 6, "Tahun Baru Islam"),
            HolidayEntry(8, 15, "Maulid Nabi Muhammad"),
            HolidayEntry(8, 17, "Hari Kemerdekaan"),
            HolidayEntry(12, 25, "Hari Natal"),
        ),
    ),
)
